// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatAreWeEating.Infrastructure;

#nullable disable

namespace WhatAreWeEating.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921074509_ModeloInicialRecetas")]
    partial class ModeloInicialRecetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Despensa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Despensas", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.DespensaIngrediente", b =>
                {
                    b.Property<Guid>("DespensaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DespensaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("DespensaIngredientes", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UnidadBase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoPublicacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.RecetaIngrediente", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecetaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("RecetaIngredientes", (string)null);
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.DespensaIngrediente", b =>
                {
                    b.HasOne("WhatAreWeEating.Recetas.Entities.Despensa", "Despensa")
                        .WithMany("DespensaIngredientes")
                        .HasForeignKey("DespensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatAreWeEating.Recetas.Entities.Ingrediente", "Ingrediente")
                        .WithMany("DespensaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Despensa");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Receta", b =>
                {
                    b.HasOne("WhatAreWeEating.Recetas.Entities.Categoria", "Categoria")
                        .WithMany("Recetas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.RecetaIngrediente", b =>
                {
                    b.HasOne("WhatAreWeEating.Recetas.Entities.Ingrediente", "Ingrediente")
                        .WithMany("RecetaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatAreWeEating.Recetas.Entities.Receta", "Receta")
                        .WithMany("RecetaIngredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Categoria", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Despensa", b =>
                {
                    b.Navigation("DespensaIngredientes");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Ingrediente", b =>
                {
                    b.Navigation("DespensaIngredientes");

                    b.Navigation("RecetaIngredientes");
                });

            modelBuilder.Entity("WhatAreWeEating.Recetas.Entities.Receta", b =>
                {
                    b.Navigation("RecetaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
