<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\WhatAreWeEating.Core\WhatAreWeEating.Core.csproj" />
    <ProjectReference Include="..\WhatAreWeEating.Recetas\WhatAreWeEating.Recetas.csproj" />
    <ProjectReference Include="..\WhatAreWeEating.Infrastructure\WhatAreWeEating.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
